from exception_handling import hello
#code under hello function is executed
